test: add unit tests for trunk based development.
solitontech/software-practices-metrics-tool pull request #103
Opened 2024-04-02 05:37 UTC by ganesh-nithin

# Why this change is required

This PR aims to add unit tests for trunk based development.

# Describe your changes

- added unit test cases.

# How this change has been tested

Tested with jest test runner.

# Reference

![image](https://github.com/solitontech/software-practices-metrics-tool/assets/127190944/e6571e30-9de6-42bc-8180-91682275b3d3)

# Checklist

- [x] I have performed a self review of my code and intend to submit as such
- [ ] I have added necessary explanations and inline comments for review
- [ ] I have considered updating necessary README or other documentations
- [x] I have added/modified necessary automated tests
- [ ] This includes a breaking changes and needs to be listed in release notes

2024-04-02 09:45 UTC, sathish-thangavel requested changes

2024-04-02 09:45 UTC, sathish-thangavel commented on server/src/use-cases/version-control/azure-devops/trunk-based-development/trunk-based-development.unit.test.js
> +describe('TrunkBasedDevelopment~getBranchMetrics - method to transform branches into following and not following branch naming standard', () => {
`method to get branches following and not following naming standard`

2024-04-02 09:45 UTC, sathish-thangavel commented on server/src/use-cases/version-control/azure-devops/trunk-based-development/trunk-based-development.unit.test.js
> +        count: 2,
Can we move this to constant

2024-04-02 09:45 UTC, sathish-thangavel commented on server/src/use-cases/version-control/azure-devops/trunk-based-development/trunk-based-development.unit.test.js
> +      percentageOfBranchesFollowingStandard: 'NaN%',
Should be fixed and should be `0%`

2024-04-02 11:05 UTC, ganesh-nithin commented on server/src/use-cases/version-control/azure-devops/trunk-based-development/trunk-based-development.unit.test.js
> +
No, Sathish. I have added them.

2024-04-02 13:56 UTC, sathish-thangavel requested changes

2024-04-02 13:56 UTC, sathish-thangavel commented on server/src/use-cases/version-control/azure-devops/trunk-based-development/trunk-based-development.js
> +      ? zeroPercentage
``0${PERCENTAGE}``

2024-04-02 13:56 UTC, sathish-thangavel commented on server/src/use-cases/version-control/azure-devops/trunk-based-development/trunk-based-development.unit.test.js
> +  AZURE_COUNT_ZERO_RESPONSE,
`import * as mock from './';`

2024-04-03 04:36 UTC, sathish-thangavel approved these changes

2024-04-03 04:36 UTC, merged