test: add unit tests for time-metrics util class.
solitontech/software-practices-metrics-tool pull request #105
Opened 2024-04-02 11:43 UTC by ganesh-nithin

# Why this change is required

This PR aims to add unit tests for TimeMetrics class.

# Describe your changes

- added tests for TimeMetrics class.

# How this change has been tested

Tested using jest test runner.

# Reference

![image](https://github.com/solitontech/software-practices-metrics-tool/assets/127190944/cdf11f9d-7a73-48d9-bc85-b32de1f44ca9)

# Checklist

- [x] I have performed a self review of my code and intend to submit as such
- [ ] I have added necessary explanations and inline comments for review
- [ ] I have considered updating necessary README or other documentations
- [x] I have added/modified necessary automated tests
- [ ] This includes a breaking changes and needs to be listed in release notes

2024-04-02 11:45 UTC, ganesh-nithin commented on server/src/use-cases/version-control/azure-devops/code-review/time-metrics/time-metrics.unit.test.js
@sathish-thangavel , can these mock data stay in the specs, the data is less.

2024-04-02 14:00 UTC, sathish-thangavel commented on server/src/use-cases/version-control/azure-devops/code-review/time-metrics/time-metrics.unit.test.js
Sure , works

2024-04-02 14:07 UTC, sathish-thangavel requested changes

2024-04-02 14:07 UTC, sathish-thangavel commented on server/src/use-cases/version-control/azure-devops/code-review/time-metrics/time-metrics.unit.test.js
> +      { id: 2, author: 'author2', timeOfVote: new Date('2022-01-01T02:00:00Z'), vote: VOTE.APPROVED },
Can we add more test case covering combination of different votes ?

2024-04-03 06:44 UTC, sathish-thangavel approved these changes
LGTM!

2024-04-03 06:44 UTC, merged